### PR TITLE
Add delete media in private API

### PR DESCRIPTION
**Pull request by AlexandruValeanu**
### Component/Part
[Private API](https://github.com/hedgedoc/hedgedoc/blob/develop/src/api/private/media/media.controller.ts)

### Description
This PR adds a method to delete media, similar to the one present in the [plublic API](https://github.com/hedgedoc/hedgedoc/blob/develop/src/api/public/media/media.controller.ts).

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
#1593

### CODE REVIEW

**Comment by davidmehren** [comment]
Thank you! :tada:

**Comment by davidmehren** [comment]
You should be able to fix the lint issue by running `yarn run format:fix`.

**Comment by AlexandruValeanu** [comment]
Done.

**Comment by AlexandruValeanu** [comment]
I am not quite sure I get the error. `username` doesn't exist on `User` so not sure why the tests think it does.

**Pull request merged**
