### PR TITLE
docs: Fix indentation of code

### PR DESCRIPTION
**Pull request by kosssi**
### Component/Part
Documentation

### Description
Fix indentation of code : https://docs.hedgedoc.org/guides/auth/nextcloud/

### CODE REVIEW

**Review by davidmehren — APPROVED** [review]

**Comment by davidmehren** [comment]
Thanks!

**Comment by kosssi** [comment]
When I check https://docs.hedgedoc.org/guides/auth/nextcloud/ it's not good, maybe you should update docs website ;)

**Comment by mrdrogdrog** [comment]
docs.hedgedoc.org doesn't show the docs from the develop branch. Only the docs from the stable master branch are deployed.

**Comment by kosssi** [comment]
Ok thanks, I will check the next release;)

**Comment by kosssi** [comment]
It's ok ;)

**Pull request merged**
