### PR TITLE
Remove cdn support

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
CDN Support

### Description
This PR removes CDN support

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
The CDN links are still present in the export templates

**Comment by davidmehren** [comment]
The only remaining place where we use a CDN is https://github.com/hedgedoc/hedgedoc/blob/master/public/js/extra.js#L632, which replaces the URLs to emoji-images with URLs to Cloudflare.

I see two ways to remove that:
- Just use the UTF-8 codepoint and hope that the user has a compatible font. That also requires to have a way to get the codepoint from the emoji name.
- Inline each emoji-image using a data URI in the  [`generateCleanHTML`](https://github.com/hedgedoc/hedgedoc/blob/master/public/js/extra.js#L615) function.

**Comment by mrdrogdrog** [comment]
I guess the data URI method would make more sense. The detection for the first is a bit to unsafe.

**Comment by ccoenen** [comment]
I would want the export to be as self-sufficient as possible.

a) I do not want to ping some CDN each time I look at a document
b) Yes it's a big company, but what if they at some point go down. Or decide to update their server names ... and so on.

**Comment by mrdrogdrog** [comment]
@ccoenen i don't get what you want to achieve with that comment. The whole reason of this pull request is to remove CDN support. Nobody argues for keeping CDN in the export 😅

**Comment by ccoenen** [comment]
yeah, me neither. Sorry for the noise. 😆

**Comment by InnayTool** [comment]
Two things in the raw export are not optimal by now:
- The exported icons are too large.
- The exported document has references to the instance from which the html was exported.

**Comment by davidmehren** [comment]
> Two things in the raw export are not optimal by now:
> 
>   - The exported icons are too large.

This is probably intended, as the raw export does not contain any CSS that would influence the emojis to be the correct size

 
>   - The exported document has references to the instance from which the html was exported.

This depends on the definition of "raw export". Currently, the export contains the exact HTML that was shown in the view-pane of the editor, but without any CSS or JavaScript. We could of course also run that through the "inline emoji images" logic, but then it would be less "raw". Also, a change here might break someone's script.

In any case, this problem has nothing to do with CDNs, so I'd like to keep it out of this PR.

**Review by InnayTool — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]

**Review by DerMolly — APPROVED** [review]

**Pull request merged**
