### PR TITLE
Permissions: Add cascade to creation and deletion

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
permissions

### Description
This PR adds cascade to permissions on creation and deletion, so permissions can be created from the note and are deleted when either the note, user or group is deleted.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### CODE REVIEW

**Comment by DerMolly** [comment]
This waits for this PR https://github.com/typeorm/typeorm/pull/7450

**Review by InnayTool — APPROVED** [review]

**Review by davidmehren — CHANGES_REQUESTED** [review]
Theres a typo in the commit message of c9832b26466d9a13ff9ccc1df425fa0efbec4183.

Cascading is one of the more 'magic' features we use, so it might be wise to document what each usage of the feature does.

**Comment by DerMolly** [comment]
> Cascading is one of the more 'magic' features we use, so it might be wise to document what each usage of the feature does.

What do you suggest?

**Comment by DerMolly** [comment]
> Theres a typo in the commit message of c9832b2.

Typo was fixed.

**Review by InnayTool — DISMISSED** [review]

**Comment by davidmehren** [comment]
> What do you suggest?

The easiest is probably to add a comment every time `cascade` is used, describing the effect.

**Comment by DerMolly** [comment]
> The easiest is probably to add a comment every time `cascade` is used, describing the effect.

Done

**Review by InnayTool — DISMISSED** [review]

**Review by davidmehren — APPROVED** [review]

**Review by InnayTool — APPROVED** [review]

**Pull request merged**
