### PR TITLE
Documentation: Add toggleable dark theme

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
docs website

### Description
This PR adds a dark theme and the toogle to switch to it. The website will follow the users preferences.

image

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### CODE REVIEW

**Comment by davidmehren** [comment]
Available at https://hedgedoc-docs-staging--dark-theme-ihrn9q81.web.app/

**Comment by davidmehren** [comment]
I think the contrast between the background and the red links is a bit low

**Comment by InnayTool** [comment]
I think the colors are not optimal. I think we should try another combination.

**Review by mrdrogdrog — CHANGES_REQUESTED** [review]

**Comment by mrdrogdrog** [comment]
I played a bit with colors. Try branch `docs/darkTheme-2`

**Comment by davidmehren** [comment]
> I played a bit with colors. Try branch docs/darkTheme-2

Deployed to https://hedgedoc-docs-staging--dark-theme2-fyambero.web.app

The contrast is way better, but we should use the logo with white text on the dark homepage. 
And is it just me or does the red link-color look weird on the dark background?

**Comment by mrdrogdrog** [comment]
It's another red because our logo red doesn't play well with the dark background.

**Comment by mrdrogdrog** [comment]
I can't change the content based on the theme. You could only swap the image with evil css magic. But that's bad

**Comment by mrdrogdrog** [comment]
Fixed the logo coloring issues.

**Comment by mrdrogdrog** [comment]
`docs/dark-theme-2` has been deleted. The changes have been added to this branch.

**Review by mrdrogdrog — APPROVED** [review]

**Review by mrdrogdrog — DISMISSED** [review]

**Review by ErikMichelson — APPROVED** [review]

**Review by mrdrogdrog — APPROVED** [review]

**Review by InnayTool — APPROVED** [review]

**Review by mrdrogdrog — APPROVED** [review]

**Review by davidmehren — APPROVED** [review]

**Pull request merged**
