### PR TITLE
feat: add realtime announcements for permission changes and note deletion

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
realtime communication

### Description
This PR adds realtime announcements for permission changes and note deletion.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
fixes https://github.com/hedgedoc/hedgedoc/issues/1984

### CODE REVIEW

**Comment by DerMolly** [comment]
This should only be reviewed after https://github.com/hedgedoc/hedgedoc/pull/2637 is merged…

**Review by InnayTool — APPROVED** [review]

**Review by davidmehren — APPROVED** [review]

**Review by InnayTool — APPROVED** [review]

**Comment by mrdrogdrog** [comment]
I don't like that you're adding another forward reference between the services to notify the realtime users. Not because of THIS reference but because this won't be the last time we'll implement a notify for realtime users. So if we keep it this way, then every time we add another message we increase the complexity and maybe even create more circular dependencies which make it harder to understand or test the app.

How about using the nestjs event system instead? https://docs.nestjs.com/techniques/events

**Comment by InnayTool** [comment]
How about merging this PR and implement the event system in another one?

**Review by mrdrogdrog — CHANGES_REQUESTED** [review]
The new public methods aren't tested

**Review by mrdrogdrog — APPROVED** [review]

**Pull request merged**
