### PR TITLE
fix: ellide css custom properties when converting css inline styles to map

### LINKED ISSUE #5596: [html-to-react] Inline CSS custom properties (e.g. `--variable`) are incorrectly transformed
### Description

thanks for all your hard work on the project, it's super useful!

react handles css custom properties that are written as inline styles by eliding them & passing them to the DOM as is. however, this project's css property conversion fails to account for custom properties (starting with `--`) & incorrectly transforms them into mangled versions of them (e.g. `--foo-bar` -> `-fooBar`).

### Steps to reproduce

```js
import { convertNodeToReactElement } from '@hedgedoc/html-to-react';
import * as cheerio from 'cheerio';

// 1. load the element with `--foo-bar`
const el = cheerio.load('<div style="--foo-bar: hello" />', {}, false).root().get(0).childNodes[0];

// 2. pass it to html-to-react
const reactEl = convertNodeToReactElement(el);

// 3. get the styles
console.log(reactEl.props.style);

// in the console you will see:
// { "-fooBar": "hello" }
```

### Expected behaviour

``` js
// in the console you should see:
// { "--foo-bar": "hello" }
```

### Logs

_No response_

### Config

_No response_

### Your Setup

- Host OS: Windows 11
- NodeJS version: v22.1.0
- HedgeDoc version: 2.1.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sxxov**
### Component/Part
react-to-html

### Description
fixes incorrectly transformed inline css custom properties

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
fixes #5596

### CODE REVIEW

**Comment by ErikMichelson** [comment]
Hey @sxxov,
thanks for your contribution!

In order to get this merged, we need you to sign-off your commits according to the contribution guidelines for the HedgeDoc organization. You can find more information on this here: https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md#certificate-of-origin

**Comment by sxxov** [comment]
> Hey @sxxov,
> 
> thanks for your contribution!
> 
> 
> 
> In order to get this merged, we need you to sign-off your commits according to the contribution guidelines for the HedgeDoc organization. You can find more information on this here: https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md#certificate-of-origin

hi! the sign-off is there, i just kinda missed it on the first commit & reattempted the commit a 2nd time (hence the 3rd merge commit). hope that still works (::

**Comment by ErikMichelson** [comment]
Hey, thanks for signing off your work!
It seems the repository got a bit messed up, so that should be resolved prior merging.

1. Run `git rebase -i HEAD~2`. This will start the rebasing process and should probably open your CLI text editor.
2. Change the second line from `pick` to `squash`. This merges your two commits (the one with sign-off and the one without). Save and exit.
3. Afterward, a text editor opens asking for the new commit message of the merged commit. Remove the duplicates, so that only your commit message is present once with your Sign-off being in the last line. Save and exit.
4. Force-push your changes to overwrite the old commits and the unnecessary merge commit: `git push --force-with-lease`

**Comment by sxxov** [comment]
@ErikMichelson thanks for the super helpful, very well written guide!! you'd be an amazing educator haha. i've done as instructed & all should be well

**Review by DerMolly — APPROVED** [review]
Looks good

**Pull request merged**
