### PR TITLE
[1.x] Add unified supported locales list

### PR DESCRIPTION
**Pull request by ErikMichelson**
### Component/Part
Language picker, i18n

### Description
When adding new languages to HedgeDoc, you had to change three different places in the app. This PR simplifies that by having a single JSON file that defines the available languages.

### Steps
- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### CODE REVIEW

**Review by DerMolly — APPROVED** [review]
I tried that and it works. The only thing that changes in contrast to the previous version is that, while switching the language the language picker is empty for a short period of time.

In my opinion nothing too problematic.

**Comment by ErikMichelson** [comment]
>  the language the language picker is empty for a short period of time.

Yes, that's due to the picker being now dynamically generated by the JS and not being hardcoded anymore.

**Comment by mrdrogdrog** [comment]
Can't you include the json during buildtime?

**Comment by mrdrogdrog** [comment]
Aka: Import the json? Like we do in the frontend?

**Comment by ErikMichelson** [comment]
That's exactly what I'm doing in this PR.

**Comment by mrdrogdrog** [comment]
Got me. I haven't read the code yet 😋

**Comment by mrdrogdrog** [comment]
Then why don't you generate it in the template?

**Pull request merged**
