### PR TITLE
Revert "config: Add a flag to control the /metrics and /status endpoints"

### PR DESCRIPTION
**Pull request by freesteph**
Reverts hedgedoc/hedgedoc#3219

Apologies there's a bug in the PR above. Hedgedoc [uses the `/config` endpoint](https://github.com/hedgedoc/hedgedoc/blob/master/public/views/includes/scripts.ejs#L1) to transmit some information client-side, via [writing into the `window` object](https://github.com/hedgedoc/hedgedoc/blob/master/public/js/lib/common/constant.ejs#L1).

Though I don't think it's a great mechanism, I don't have a patch yet to work around it, so revert the previous PR in the meantime.

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
*sigh* i hate the 1.x code so much... 


Please sign off the commit.

**Comment by mrdrogdrog** [comment]
It's okay. There is a reason why we're rewriting this unpredictable mess 🙃

**Comment by mrdrogdrog** [comment]
Tbh: I don't think that it's necessary to revert EVERYTHING. Just revert the code for deactivation of the status route and keep the code that deactivates the metrics route.

**Review by mrdrogdrog — APPROVED** [review]

**Review by DerMolly — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]

**Comment by mrdrogdrog** [comment]
I've merged this PR to repair the master branch. If you still want to deactivate the metric route then feel free to create a new PR.

**Comment by freesteph** [comment]
Sorry I was busy this weekend, I'll push a new PR soon. Thanks for taking care of this!

**Pull request merged**
